/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StatutoryRecord = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'epfEmployeeContribution' : IDL.Float64,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'esiEmployeeContribution' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'employeeId' : IDL.Nat,
  'epfEmployerContribution' : IDL.Float64,
  'basicSalary' : IDL.Float64,
  'esiEmployerContribution' : IDL.Float64,
});
export const LeaveStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LeaveType = IDL.Variant({
  'cl' : IDL.Null,
  'pl' : IDL.Null,
  'sl' : IDL.Null,
});
export const LeaveRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeaveStatus,
  'appliedOn' : IDL.Text,
  'createdAt' : IDL.Int,
  'reviewedBy' : IDL.Principal,
  'reviewedOn' : IDL.Text,
  'toDate' : IDL.Text,
  'updatedAt' : IDL.Int,
  'employeeId' : IDL.Nat,
  'fromDate' : IDL.Text,
  'leaveType' : LeaveType,
  'reason' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceStatus = IDL.Variant({
  'halfDay' : IDL.Null,
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'employeeId' : IDL.Nat,
  'notes' : IDL.Text,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'createdAt' : IDL.Int,
  'joiningDate' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'employeeId' : IDL.Text,
  'phone' : IDL.Text,
  'pfAccountNumber' : IDL.Text,
  'department' : IDL.Text,
  'uanNumber' : IDL.Text,
  'esiNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Nat),
});
export const DashboardStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'presentToday' : IDL.Nat,
  'activeEmployees' : IDL.Nat,
  'pendingLeaves' : IDL.Nat,
});
export const LeaveBalance = IDL.Record({
  'id' : IDL.Nat,
  'plTotal' : IDL.Nat,
  'plUsed' : IDL.Nat,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'slUsed' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'slTotal' : IDL.Nat,
  'employeeId' : IDL.Nat,
  'clTotal' : IDL.Nat,
  'clUsed' : IDL.Nat,
});
export const LeaveQuota = IDL.Record({
  'clQuota' : IDL.Nat,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'plQuota' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'slQuota' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStatutoryRecord' : IDL.Func([StatutoryRecord], [IDL.Nat], []),
  'applyLeaveRequest' : IDL.Func([LeaveRequest], [IDL.Nat], []),
  'approveLeaveRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkMarkAttendance' : IDL.Func(
      [IDL.Vec(AttendanceRecord)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'createEmployee' : IDL.Func([Employee], [IDL.Nat], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByEmployee' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEmployeeById' : IDL.Func([IDL.Nat], [Employee], ['query']),
  'getLeaveBalance' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(LeaveBalance)], []),
  'getLeaveQuota' : IDL.Func([IDL.Nat], [IDL.Opt(LeaveQuota)], ['query']),
  'getLeaveRequestsByEmployee' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaveRequest)],
      ['query'],
    ),
  'getLeaveRequestsByStatus' : IDL.Func(
      [LeaveStatus],
      [IDL.Vec(LeaveRequest)],
      ['query'],
    ),
  'getStatutoryByEmployee' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StatutoryRecord)],
      ['query'],
    ),
  'getStatutoryByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(StatutoryRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([AttendanceRecord], [IDL.Nat], []),
  'rejectLeaveRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEmployees' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'setLeaveQuota' : IDL.Func([IDL.Nat, LeaveQuota], [], []),
  'updateEmployee' : IDL.Func([IDL.Nat, Employee], [], []),
  'updateLeaveBalance' : IDL.Func([LeaveBalance], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StatutoryRecord = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'epfEmployeeContribution' : IDL.Float64,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'esiEmployeeContribution' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'employeeId' : IDL.Nat,
    'epfEmployerContribution' : IDL.Float64,
    'basicSalary' : IDL.Float64,
    'esiEmployerContribution' : IDL.Float64,
  });
  const LeaveStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LeaveType = IDL.Variant({
    'cl' : IDL.Null,
    'pl' : IDL.Null,
    'sl' : IDL.Null,
  });
  const LeaveRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeaveStatus,
    'appliedOn' : IDL.Text,
    'createdAt' : IDL.Int,
    'reviewedBy' : IDL.Principal,
    'reviewedOn' : IDL.Text,
    'toDate' : IDL.Text,
    'updatedAt' : IDL.Int,
    'employeeId' : IDL.Nat,
    'fromDate' : IDL.Text,
    'leaveType' : LeaveType,
    'reason' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceStatus = IDL.Variant({
    'halfDay' : IDL.Null,
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'employeeId' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'createdAt' : IDL.Int,
    'joiningDate' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'employeeId' : IDL.Text,
    'phone' : IDL.Text,
    'pfAccountNumber' : IDL.Text,
    'department' : IDL.Text,
    'uanNumber' : IDL.Text,
    'esiNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Nat),
  });
  const DashboardStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'presentToday' : IDL.Nat,
    'activeEmployees' : IDL.Nat,
    'pendingLeaves' : IDL.Nat,
  });
  const LeaveBalance = IDL.Record({
    'id' : IDL.Nat,
    'plTotal' : IDL.Nat,
    'plUsed' : IDL.Nat,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'slUsed' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'slTotal' : IDL.Nat,
    'employeeId' : IDL.Nat,
    'clTotal' : IDL.Nat,
    'clUsed' : IDL.Nat,
  });
  const LeaveQuota = IDL.Record({
    'clQuota' : IDL.Nat,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'plQuota' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'slQuota' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStatutoryRecord' : IDL.Func([StatutoryRecord], [IDL.Nat], []),
    'applyLeaveRequest' : IDL.Func([LeaveRequest], [IDL.Nat], []),
    'approveLeaveRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkMarkAttendance' : IDL.Func(
        [IDL.Vec(AttendanceRecord)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'createEmployee' : IDL.Func([Employee], [IDL.Nat], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByEmployee' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEmployeeById' : IDL.Func([IDL.Nat], [Employee], ['query']),
    'getLeaveBalance' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(LeaveBalance)],
        [],
      ),
    'getLeaveQuota' : IDL.Func([IDL.Nat], [IDL.Opt(LeaveQuota)], ['query']),
    'getLeaveRequestsByEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getLeaveRequestsByStatus' : IDL.Func(
        [LeaveStatus],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getStatutoryByEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StatutoryRecord)],
        ['query'],
      ),
    'getStatutoryByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(StatutoryRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([AttendanceRecord], [IDL.Nat], []),
    'rejectLeaveRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEmployees' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'setLeaveQuota' : IDL.Func([IDL.Nat, LeaveQuota], [], []),
    'updateEmployee' : IDL.Func([IDL.Nat, Employee], [], []),
    'updateLeaveBalance' : IDL.Func([LeaveBalance], [], []),
  });
};

export const init = ({ IDL }) => { return []; };