/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'status' : AttendanceStatus,
  'date' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'employeeId' : bigint,
  'notes' : string,
}
export type AttendanceStatus = { 'halfDay' : null } |
  { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface DashboardStats {
  'totalEmployees' : bigint,
  'presentToday' : bigint,
  'activeEmployees' : bigint,
  'pendingLeaves' : bigint,
}
export interface Employee {
  'id' : bigint,
  'name' : string,
  'designation' : string,
  'createdAt' : bigint,
  'joiningDate' : string,
  'isActive' : boolean,
  'email' : string,
  'updatedAt' : bigint,
  'employeeId' : string,
  'phone' : string,
  'pfAccountNumber' : string,
  'department' : string,
  'uanNumber' : string,
  'esiNumber' : string,
}
export interface LeaveBalance {
  'id' : bigint,
  'plTotal' : bigint,
  'plUsed' : bigint,
  'createdAt' : bigint,
  'year' : bigint,
  'slUsed' : bigint,
  'updatedAt' : bigint,
  'slTotal' : bigint,
  'employeeId' : bigint,
  'clTotal' : bigint,
  'clUsed' : bigint,
}
export interface LeaveQuota {
  'clQuota' : bigint,
  'createdAt' : bigint,
  'year' : bigint,
  'plQuota' : bigint,
  'updatedAt' : bigint,
  'slQuota' : bigint,
}
export interface LeaveRequest {
  'id' : bigint,
  'status' : LeaveStatus,
  'appliedOn' : string,
  'createdAt' : bigint,
  'reviewedBy' : Principal,
  'reviewedOn' : string,
  'toDate' : string,
  'updatedAt' : bigint,
  'employeeId' : bigint,
  'fromDate' : string,
  'leaveType' : LeaveType,
  'reason' : string,
}
export type LeaveStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type LeaveType = { 'cl' : null } |
  { 'pl' : null } |
  { 'sl' : null };
export interface StatutoryRecord {
  'id' : bigint,
  'month' : bigint,
  'epfEmployeeContribution' : number,
  'createdAt' : bigint,
  'year' : bigint,
  'esiEmployeeContribution' : number,
  'updatedAt' : bigint,
  'employeeId' : bigint,
  'epfEmployerContribution' : number,
  'basicSalary' : number,
  'esiEmployerContribution' : number,
}
export interface UserProfile { 'name' : string, 'employeeId' : [] | [bigint] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStatutoryRecord' : ActorMethod<[StatutoryRecord], bigint>,
  'applyLeaveRequest' : ActorMethod<[LeaveRequest], bigint>,
  'approveLeaveRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkMarkAttendance' : ActorMethod<[Array<AttendanceRecord>], Array<bigint>>,
  'createEmployee' : ActorMethod<[Employee], bigint>,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByEmployee' : ActorMethod<
    [bigint, bigint, bigint],
    Array<AttendanceRecord>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEmployeeById' : ActorMethod<[bigint], Employee>,
  'getLeaveBalance' : ActorMethod<[bigint, bigint], [] | [LeaveBalance]>,
  'getLeaveQuota' : ActorMethod<[bigint], [] | [LeaveQuota]>,
  'getLeaveRequestsByEmployee' : ActorMethod<[bigint], Array<LeaveRequest>>,
  'getLeaveRequestsByStatus' : ActorMethod<[LeaveStatus], Array<LeaveRequest>>,
  'getStatutoryByEmployee' : ActorMethod<[bigint], Array<StatutoryRecord>>,
  'getStatutoryByMonth' : ActorMethod<[bigint, bigint], Array<StatutoryRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[AttendanceRecord], bigint>,
  'rejectLeaveRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEmployees' : ActorMethod<[string], Array<Employee>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'setLeaveQuota' : ActorMethod<[bigint, LeaveQuota], undefined>,
  'updateEmployee' : ActorMethod<[bigint, Employee], undefined>,
  'updateLeaveBalance' : ActorMethod<[LeaveBalance], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];