/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaveRequest {
    id: bigint;
    status: LeaveStatus;
    appliedOn: string;
    createdAt: bigint;
    reviewedBy: Principal;
    reviewedOn: string;
    toDate: string;
    updatedAt: bigint;
    employeeId: bigint;
    fromDate: string;
    leaveType: LeaveType;
    reason: string;
}
export interface LeaveQuota {
    clQuota: bigint;
    createdAt: bigint;
    year: bigint;
    plQuota: bigint;
    updatedAt: bigint;
    slQuota: bigint;
}
export interface StatutoryRecord {
    id: bigint;
    month: bigint;
    epfEmployeeContribution: number;
    createdAt: bigint;
    year: bigint;
    esiEmployeeContribution: number;
    updatedAt: bigint;
    employeeId: bigint;
    epfEmployerContribution: number;
    basicSalary: number;
    esiEmployerContribution: number;
}
export interface Employee {
    id: bigint;
    name: string;
    designation: string;
    createdAt: bigint;
    joiningDate: string;
    isActive: boolean;
    email: string;
    updatedAt: bigint;
    employeeId: string;
    phone: string;
    pfAccountNumber: string;
    department: string;
    uanNumber: string;
    esiNumber: string;
}
export interface AttendanceRecord {
    id: bigint;
    status: AttendanceStatus;
    date: string;
    createdAt: bigint;
    updatedAt: bigint;
    employeeId: bigint;
    notes: string;
}
export interface LeaveBalance {
    id: bigint;
    plTotal: bigint;
    plUsed: bigint;
    createdAt: bigint;
    year: bigint;
    slUsed: bigint;
    updatedAt: bigint;
    slTotal: bigint;
    employeeId: bigint;
    clTotal: bigint;
    clUsed: bigint;
}
export interface UserProfile {
    name: string;
    employeeId?: bigint;
}
export interface DashboardStats {
    totalEmployees: bigint;
    presentToday: bigint;
    activeEmployees: bigint;
    pendingLeaves: bigint;
}
export enum AttendanceStatus {
    halfDay = "halfDay",
    present = "present",
    late = "late",
    absent = "absent"
}
export enum LeaveStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum LeaveType {
    cl = "cl",
    pl = "pl",
    sl = "sl"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addStatutoryRecord(record: StatutoryRecord): Promise<bigint>;
    applyLeaveRequest(request: LeaveRequest): Promise<bigint>;
    approveLeaveRequest(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkMarkAttendance(records: Array<AttendanceRecord>): Promise<Array<bigint>>;
    createEmployee(employee: Employee): Promise<bigint>;
    deleteEmployee(id: bigint): Promise<void>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAttendanceByDate(date: string): Promise<Array<AttendanceRecord>>;
    getAttendanceByEmployee(employeeId: bigint, month: bigint, year: bigint): Promise<Array<AttendanceRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getEmployeeById(id: bigint): Promise<Employee>;
    getLeaveBalance(employeeId: bigint, year: bigint): Promise<LeaveBalance | null>;
    getLeaveQuota(year: bigint): Promise<LeaveQuota | null>;
    getLeaveRequestsByEmployee(employeeId: bigint): Promise<Array<LeaveRequest>>;
    getLeaveRequestsByStatus(status: LeaveStatus): Promise<Array<LeaveRequest>>;
    getStatutoryByEmployee(employeeId: bigint): Promise<Array<StatutoryRecord>>;
    getStatutoryByMonth(month: bigint, year: bigint): Promise<Array<StatutoryRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(record: AttendanceRecord): Promise<bigint>;
    rejectLeaveRequest(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchEmployees(searchTerm: string): Promise<Array<Employee>>;
    seedSampleData(): Promise<void>;
    setLeaveQuota(year: bigint, quota: LeaveQuota): Promise<void>;
    updateEmployee(id: bigint, employee: Employee): Promise<void>;
    updateLeaveBalance(balance: LeaveBalance): Promise<void>;
}
import type { AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, LeaveBalance as _LeaveBalance, LeaveQuota as _LeaveQuota, LeaveRequest as _LeaveRequest, LeaveStatus as _LeaveStatus, LeaveType as _LeaveType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addStatutoryRecord(arg0: StatutoryRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStatutoryRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStatutoryRecord(arg0);
            return result;
        }
    }
    async applyLeaveRequest(arg0: LeaveRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.applyLeaveRequest(to_candid_LeaveRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyLeaveRequest(to_candid_LeaveRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveLeaveRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLeaveRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkMarkAttendance(arg0: Array<AttendanceRecord>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkMarkAttendance(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkMarkAttendance(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEmployee(arg0: Employee): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return result;
        }
    }
    async getAttendanceByDate(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDate(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDate(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByEmployee(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByEmployee(arg0, arg1, arg2);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByEmployee(arg0, arg1, arg2);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getEmployeeById(arg0: bigint): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeById(arg0);
            return result;
        }
    }
    async getLeaveBalance(arg0: bigint, arg1: bigint): Promise<LeaveBalance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveBalance(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveBalance(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveQuota(arg0: bigint): Promise<LeaveQuota | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveQuota(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveQuota(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveRequestsByEmployee(arg0: bigint): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequestsByEmployee(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequestsByEmployee(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveRequestsByStatus(arg0: LeaveStatus): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequestsByStatus(to_candid_LeaveStatus_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequestsByStatus(to_candid_LeaveStatus_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatutoryByEmployee(arg0: bigint): Promise<Array<StatutoryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatutoryByEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatutoryByEmployee(arg0);
            return result;
        }
    }
    async getStatutoryByMonth(arg0: bigint, arg1: bigint): Promise<Array<StatutoryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatutoryByMonth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatutoryByMonth(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: AttendanceRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(to_candid_AttendanceRecord_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(to_candid_AttendanceRecord_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectLeaveRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectLeaveRequest(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchEmployees(arg0: string): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEmployees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEmployees(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async setLeaveQuota(arg0: bigint, arg1: LeaveQuota): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLeaveQuota(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLeaveQuota(arg0, arg1);
            return result;
        }
    }
    async updateEmployee(arg0: bigint, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, arg1);
            return result;
        }
    }
    async updateLeaveBalance(arg0: LeaveBalance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveBalance(arg0);
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveRequest): LeaveRequest {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveType): LeaveType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaveBalance]): LeaveBalance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaveQuota]): LeaveQuota | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AttendanceStatus;
    date: string;
    createdAt: bigint;
    updatedAt: bigint;
    employeeId: bigint;
    notes: string;
}): {
    id: bigint;
    status: AttendanceStatus;
    date: string;
    createdAt: bigint;
    updatedAt: bigint;
    employeeId: bigint;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n17(_uploadFile, _downloadFile, value.status),
        date: value.date,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        employeeId: value.employeeId,
        notes: value.notes
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId: [] | [bigint];
}): {
    name: string;
    employeeId?: bigint;
} {
    return {
        name: value.name,
        employeeId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeaveStatus;
    appliedOn: string;
    createdAt: bigint;
    reviewedBy: Principal;
    reviewedOn: string;
    toDate: string;
    updatedAt: bigint;
    employeeId: bigint;
    fromDate: string;
    leaveType: _LeaveType;
    reason: string;
}): {
    id: bigint;
    status: LeaveStatus;
    appliedOn: string;
    createdAt: bigint;
    reviewedBy: Principal;
    reviewedOn: string;
    toDate: string;
    updatedAt: bigint;
    employeeId: bigint;
    fromDate: string;
    leaveType: LeaveType;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_LeaveStatus_n30(_uploadFile, _downloadFile, value.status),
        appliedOn: value.appliedOn,
        createdAt: value.createdAt,
        reviewedBy: value.reviewedBy,
        reviewedOn: value.reviewedOn,
        toDate: value.toDate,
        updatedAt: value.updatedAt,
        employeeId: value.employeeId,
        fromDate: value.fromDate,
        leaveType: from_candid_LeaveType_n32(_uploadFile, _downloadFile, value.leaveType),
        reason: value.reason
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    halfDay: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "halfDay" in value ? AttendanceStatus.halfDay : "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LeaveStatus {
    return "pending" in value ? LeaveStatus.pending : "approved" in value ? LeaveStatus.approved : "rejected" in value ? LeaveStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cl: null;
} | {
    pl: null;
} | {
    sl: null;
}): LeaveType {
    return "cl" in value ? LeaveType.cl : "pl" in value ? LeaveType.pl : "sl" in value ? LeaveType.sl : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveRequest>): Array<LeaveRequest> {
    return value.map((x)=>from_candid_LeaveRequest_n28(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceRecord): _AttendanceRecord {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveRequest): _LeaveRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): _LeaveStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): _LeaveType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: AttendanceStatus;
    date: string;
    createdAt: bigint;
    updatedAt: bigint;
    employeeId: bigint;
    notes: string;
}): {
    id: bigint;
    status: _AttendanceStatus;
    date: string;
    createdAt: bigint;
    updatedAt: bigint;
    employeeId: bigint;
    notes: string;
} {
    return {
        id: value.id,
        status: to_candid_AttendanceStatus_n12(_uploadFile, _downloadFile, value.status),
        date: value.date,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        employeeId: value.employeeId,
        notes: value.notes
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: LeaveStatus;
    appliedOn: string;
    createdAt: bigint;
    reviewedBy: Principal;
    reviewedOn: string;
    toDate: string;
    updatedAt: bigint;
    employeeId: bigint;
    fromDate: string;
    leaveType: LeaveType;
    reason: string;
}): {
    id: bigint;
    status: _LeaveStatus;
    appliedOn: string;
    createdAt: bigint;
    reviewedBy: Principal;
    reviewedOn: string;
    toDate: string;
    updatedAt: bigint;
    employeeId: bigint;
    fromDate: string;
    leaveType: _LeaveType;
    reason: string;
} {
    return {
        id: value.id,
        status: to_candid_LeaveStatus_n3(_uploadFile, _downloadFile, value.status),
        appliedOn: value.appliedOn,
        createdAt: value.createdAt,
        reviewedBy: value.reviewedBy,
        reviewedOn: value.reviewedOn,
        toDate: value.toDate,
        updatedAt: value.updatedAt,
        employeeId: value.employeeId,
        fromDate: value.fromDate,
        leaveType: to_candid_LeaveType_n5(_uploadFile, _downloadFile, value.leaveType),
        reason: value.reason
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId?: bigint;
}): {
    name: string;
    employeeId: [] | [bigint];
} {
    return {
        name: value.name,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    halfDay: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.halfDay ? {
        halfDay: null
    } : value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.late ? {
        late: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == LeaveStatus.pending ? {
        pending: null
    } : value == LeaveStatus.approved ? {
        approved: null
    } : value == LeaveStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): {
    cl: null;
} | {
    pl: null;
} | {
    sl: null;
} {
    return value == LeaveType.cl ? {
        cl: null
    } : value == LeaveType.pl ? {
        pl: null
    } : value == LeaveType.sl ? {
        sl: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AttendanceRecord>): Array<_AttendanceRecord> {
    return value.map((x)=>to_candid_AttendanceRecord_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
